### PR TITLE
Convert plus signs to spaces

### LINKED ISSUE #7: Does not decode plus signs
This test fails:

```js
describe('#parse', function () {
  it('will decode plus signs', function () {
    var obj = qs.parse('foo+bar=baz+qux');

    assume(obj).is.a('object');
    assume(obj["foo bar"]).equals('baz qux');
  });
});
```

### PR DESCRIPTION
**Pull request by lpinca**
Fixes #7

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -3,6 +3,17 @@
...
 
 /**
+ * Decode a URI encoded string.
+ *
+ * @param {String} input The URI encoded string.
+ * @returns {String} The decoded string.
+ * @api private
+ */
+function decode(input) {
+  return decodeURIComponent(input).replace(/\+/g, ' ');
```
Comment (pschultz) [inline index.js]: You have to replace before encoding, otherwise encoded plus signs get replace too:

```js
      var obj = qs.parse('foo+bar=baz%2Bqux');

      assume(obj).is.a('object');
      assume(obj['foo bar']).equals('baz+qux');
```

Comment (lpinca) [inline index.js]: Ops, you are right, thanks.
